spring.application.name=jobapp
# Enables the H2 database web UI
spring.h2.console.enabled=true
# Creates an H2 database named 'test' that lives only in memory
# and is deleted when the application stops
spring.datasource.url=jdbc:h2:mem:test